main: fr.discowzombie.invcleaner.InvCleaner
name: InvCleaner
author: DiscowZombie
version: 1.0
description: Permet de nettoyer l'inventaire de facon avance.
website: https://github.com/DiscowZombie/InvCleaner
commands:
    invremove: